language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: nightly

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit
